
author: Ricardo SIGNES <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.60
license: perl
name: Sub-Exporter
no_index: 
  directory: 
    - inc
    - t
requires: 
  Sub::Install: 0.03
version: 0.90
