author: 'Ricardo SIGNES <rjbs@cpan.org>'
distribution_type: module
generated_by: Module::Install version 0.62
license: perl
name: Sub-Exporter
no_index:
  directory:
    - inc
    - t
requires:
  Data::OptList: 0.1
  Params::Util: 0.14
  Sub::Install: 0.92
version: 0.961
