
author: Ricardo SIGNES <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.60
license: perl
name: Sub-Exporter
no_index: 
  directory: 
    - inc
    - t
requires: 
  List::Util: 0
  Scalar::Util: 0
  Sub::Install: 0.91
version: 0.952
