---
abstract: 'a sophisticated exporter for custom-built routines'
author:
  - 'Ricardo Signes <rjbs@cpan.org>'
build_requires:
  Exporter: 0
  Test::More: 0.96
  overload: 0
  subs: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Exporter
requires:
  Carp: 0
  Data::OptList: 0.100
  Params::Util: 0.14
  Sub::Install: 0.92
  perl: 5.006
resources:
  repository: git://git.codesimply.com/Sub-Exporter.git
version: 0.983
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@RJBS/@Basic/GatherDir'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@RJBS/@Basic/PruneCruft'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@RJBS/@Basic/ManifestSkip'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@RJBS/@Basic/MetaYAML'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::License
      name: '@RJBS/@Basic/License'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@RJBS/@Basic/Readme'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@RJBS/@Basic/ExtraTests'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@RJBS/@Basic/ExecDir'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@RJBS/@Basic/ShareDir'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@RJBS/@Basic/MakeMaker'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@RJBS/@Basic/Manifest'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@RJBS/@Basic/TestRelease'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@RJBS/@Basic/ConfirmRelease'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@RJBS/@Basic/UploadToCPAN'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@RJBS/AutoPrereqs'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@RJBS/Git::NextVersion'
      version: 1.103520
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@RJBS/PkgVersion'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@RJBS/MetaConfig'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@RJBS/MetaJSON'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@RJBS/NextRelease'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@RJBS/PodSyntaxTests'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@RJBS/Repository'
      version: 0.17
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@RJBS/TestMoreWithSubtests'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@RJBS/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@RJBS/@Git/Check'
      version: 1.103520
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@RJBS/@Git/Commit'
      version: 1.103520
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@RJBS/@Git/Tag'
      version: 1.103520
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@RJBS/@Git/Push'
      version: 1.103520
    -
      class: Dist::Zilla::Plugin::RemovePrereqs
      config:
        Dist::Zilla::Plugin::RemovePrereqs:
          modules_to_remove:
            - E::Parent
            - Package::Generator
      name: RemovePrereqs
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.200001
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.200001
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 1
    version: 4.200001
